### ISSUE TITLE
Dictionary Error

### ISSUE THREAD

**Issue by tuday2** [stmrocket/ha-smartmetertexas#10]
expected a dictionary for dictionary value @ data['packages']['sensor']

Config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages

smartmetertexas.yaml is in config directory/packages/smartmetertexas/smartmetertexas.yaml

Can't figure out what is causing the error

**Comment by stmrocket** [comment]
My package line is as follows and is working:
``packages: !include_dir_named packages``
I can't remember why I went with that option back when I set up packages...

**Comment by tuday2** [comment]
wow that seemed to do the trick, i'm in business. Thanks!
