### ISSUE TITLE
No Readings are Returned

### ISSUE THREAD

**Issue by stmrocket** [stmrocket/ha-smartmetertexas#11]
As of this morning, no meter readings have been returned from the flow.  Upon monitoring the debug endpoints, the authentication process executes correctly, but the read meter request is returning an error to try again later.

This is likely a server problem that will self resolve, but may indicate that endpoints have changed and will need updating.

**Comment by stmrocket** [comment]
This issue appears to have been caused by server work by Smart Meter Texas.  Everything is now working again with no changes to the code.

**Comment by daviswieck** [comment]
It appears this could be happening again... Last data it grabbed was on Nov. 11 at 11:50pm... Nothing since then. 

Getting an "ECONNRESET" error on the "Log In" node and "Request Read" Node. 

Running HA 2022.11.2 through virtual machine.
